services:
  - type: web
    name: genewise-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_PASS
        sync: false
